//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimebanksNZ.DAL.MySqlDb.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class category
    {
        public int id_category { get; set; }
        public string name { get; set; }
        public Nullable<System.DateTime> dateadded { get; set; }
        public Nullable<int> parent_id { get; set; }
    }
}
