//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Timebanks.NZ.DAL.MySqlDb.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class country
    {
        public int id_country { get; set; }
        public string name { get; set; }
        public string abbreviation { get; set; }
        public System.DateTime date_added { get; set; }
        public double geo_long { get; set; }
        public double geo_lat { get; set; }
    }
}
