//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Timebanks.NZ.DAL.MySql.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class permission
    {
        public permission()
        {
            this.member_permission = new HashSet<member_permission>();
        }
    
        public int id_permission { get; set; }
        public System.DateTime created { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<member_permission> member_permission { get; set; }
    }
}
