//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Timebanks.NZ.DAL.MySqlDb.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class tag
    {
        public int id_tag { get; set; }
        public Nullable<System.Guid> id_member { get; set; }
        public Nullable<int> id_offer_need { get; set; }
        public string name { get; set; }
    
        public virtual member member { get; set; }
        public virtual offer_need offer_need { get; set; }
    }
}
