//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Timebanks.NZ.DAL.MySqlDb.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class timebank
    {
        public timebank()
        {
            this.members = new HashSet<member>();
            this.offer_need = new HashSet<offer_need>();
        }
    
        public int id_timebank { get; set; }
        public string name { get; set; }
        public string url { get; set; }
        public Nullable<double> geo_long { get; set; }
        public Nullable<double> geo_lat { get; set; }
        public string suburb { get; set; }
        public string city { get; set; }
        public Nullable<bool> is_member_timebanknz { get; set; }
        public Nullable<int> id_country { get; set; }
        public Nullable<int> id_theme { get; set; }
        public string address_1 { get; set; }
        public string address_2 { get; set; }
        public string postcode { get; set; }
    
        public virtual ICollection<member> members { get; set; }
        public virtual ICollection<offer_need> offer_need { get; set; }
    }
}
