//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Timebanks.NZ.DAL.MySql.EntityFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class timebanksEntities : DbContext
    {
        public timebanksEntities()
            : base("name=timebanksEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<category> categories { get; set; }
        public virtual DbSet<country> countries { get; set; }
        public virtual DbSet<member> members { get; set; }
        public virtual DbSet<member_permission> member_permission { get; set; }
        public virtual DbSet<offer_need> offer_need { get; set; }
        public virtual DbSet<permission> permissions { get; set; }
        public virtual DbSet<tag> tags { get; set; }
        public virtual DbSet<timebank> timebanks { get; set; }
        public virtual DbSet<trade> trades { get; set; }
    }
}
